name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Aquí puedes agregar comandos para construir tu proyecto, ejecutar pruebas, etc.
      # Por ejemplo:
      # - name: Build
      #   run: npm install && npm run build

      # - name: Run tests
      #   run: npm test
